Fix compilation error on Arch Linux
On Arch Linux with hdf5 1.14.4.2 and GCC 14.1.1 the `hsize_t` type is `unsigned long`
instead of `unsigned long long`, which causes a compilation error.

```
convert.c: In function ‘R_reorder’:
convert.c:1586:24: error: initialization of ‘hsize_t *’ {aka ‘long unsigned int *’} from incompatible pointer type ‘long long unsigned int *’ [-Wincompatible-pointer-types]
 1586 |   hsize_t* new_order = (unsigned long long *) VOIDPTR(R_helper);
      |                        ^
```